import SwiftUI

struct colorResource {
    
    static let primary_200 = Color(hex: "#beca5d")
    static let primary_500 = Color(hex: "#a8b44c")
    static let primary_700 = Color(hex: "#8a9535")
    static let black = Color(hex: "#000000")
    static let grey = Color(hex: "#a2a2a2")
    static let cc = Color(hex: "#CCCCCC")
    static let ee = Color(hex: "#EEEEEE")
    static let white = Color(hex: "#FFFFFF")
    static let ddl = Color(hex: "#9D000000")
    static let error = Color(hex: "#0000")
    static let orange = Color(hex: "#FF9e00")
    static let success = Color(hex: "#28a745")
    static let successBG = Color(hex: "#d4edda")
    static let danger = Color(hex: "#dc3545")
    static let dangerBG = Color(hex: "#f8d7da")
    static let maroon = Color(hex: "#b23a00")
    static let maroonBG = Color(hex: "#edddd2")
    static let lightButton = Color(hex: "#e6e4bf")
    static let lightButtonText = Color(hex: "#3a3a3a")
    static let lightBar = Color(hex: "#f0eddd")
    static let letterColor = Color(hex: "#1f88cf")
    static let verseColor = Color(hex: "#f7f8ea")
    static let verseSelected = Color(hex: "#d8ddb6")
    static let ayahNumber = Color(hex: "#13509b")
    static let darkBlue = Color(hex: "#465967")
    static let transparent = Color(hex: "#00FFFFFF")
    static let textFieldBG = Color(hex: "#F2F4E4")
    static let greyButtonText = Color(hex: "#F1F1F1")
    static let greyButtonBG = Color(hex: "#c2c2c2")
}
